# Generated by Django 4.2.5 on 2023-09-04 15:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='age',
            field=models.CharField(default=datetime.datetime(2023, 9, 4, 15, 47, 36, 362916, tzinfo=datetime.timezone.utc), max_length=2),
            preserve_default=False,
        ),
    ]
