# Generated by Django 4.2.5 on 2023-09-04 16:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_candidate_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='phone',
            field=models.CharField(default=datetime.datetime(2023, 9, 4, 16, 40, 32, 812710, tzinfo=datetime.timezone.utc), max_length=25),
            preserve_default=False,
        ),
    ]
