# Generated by Django 4.2.5 on 2023-09-04 20:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_candidate_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='job',
            field=models.CharField(default=datetime.datetime(2023, 9, 4, 20, 46, 17, 718272, tzinfo=datetime.timezone.utc), max_length=5),
            preserve_default=False,
        ),
    ]
