# Generated by Django 4.2.5 on 2023-09-04 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_candidate_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='situation',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Disapproved', 'Disapproved')], default='Pending', max_length=50, null=True),
        ),
    ]
