# Generated by Django 4.2.5 on 2023-09-05 17:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_candidate_experience_candidate_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='file',
            field=models.FileField(default=datetime.datetime(2023, 9, 5, 17, 25, 11, 379417, tzinfo=datetime.timezone.utc), upload_to=''),
            preserve_default=False,
        ),
    ]
