# Generated by Django 4.2.5 on 2023-09-05 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_candidate_databases_candidate_frameworks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='situation',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=50, null=True),
        ),
    ]
