# Generated by Django 4.2.5 on 2023-09-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_alter_candidate_situation'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='company_note',
            field=models.TextField(blank=True),
        ),
    ]
