# Generated by Django 4.2.5 on 2023-09-07 11:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_candidate_company_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='age',
        ),
        migrations.AddField(
            model_name='candidate',
            name='birth',
            field=models.DateField(default=datetime.datetime(2023, 9, 7, 11, 55, 36, 350368, tzinfo=datetime.timezone.utc), verbose_name='Birthday'),
            preserve_default=False,
        ),
    ]
