# Generated by Django 4.2.5 on 2023-09-07 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_candidate_about_course_candidate_about_job_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='image',
            field=models.ImageField(blank=True, upload_to='photo', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='file',
            field=models.FileField(blank=True, upload_to='resume', verbose_name='Resume'),
        ),
    ]
