# Generated by Django 4.2.5 on 2023-09-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_alter_candidate_job_alter_candidate_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='smoker',
            field=models.CharField(choices=[('1', 'Yes'), ('2', 'No')], default='', max_length=10),
        ),
    ]
