# Generated by Django 4.2.5 on 2023-09-12 08:24

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_alter_candidate_smoker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='databases',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('MySql', 'MySql'), ('Postgree', 'Postgree'), ('MongoDB', 'MongoDB'), ('Sqlite3', 'Sqlite3'), ('Oracle', 'Oracle'), ('Others', 'Others')], max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='frameworks',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Laravel', 'Laravel'), ('Angular', 'Angular'), ('Django', 'Django'), ('Flask', 'Flask'), ('Vue', 'Vue'), ('Others', 'Others')], max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='languages',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Python', 'Python'), ('Javascript', 'Javascript'), ('Java', 'Java'), ('C++', 'C++'), ('Ruby', 'Ruby'), ('Others', 'Others')], max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='libraries',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Ajax', 'Ajax'), ('Jquery', 'Jquery'), ('React.js', 'React.js'), ('Chart.js', 'Chart.js'), ('Gsap', 'Gsap'), ('Others', 'Others')], max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='mobile',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('React native', 'React native'), ('Kivy', 'Kivy'), ('Flutter', 'Flutter'), ('Ionic', 'Ionic'), ('Xamarim', 'Xamarim'), ('Others', 'Others')], max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='others',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('UML', 'UML'), ('SQL', 'SQL'), ('Docker', 'Docker'), ('GIT', 'GIT'), ('GraphQL', 'GraphQL'), ('Others', 'Others')], max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='status_course',
            field=models.CharField(choices=[('', 'Select your status'), ("I'm studying", "I'm studying"), ('I took a break', 'I took a break'), ('Completed', 'Completed')], max_length=50, null=True),
        ),
    ]
