# Generated by Django 4.2.5 on 2023-09-14 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0019_email_employee_email_sent_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='finished_course',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='finished_job',
            field=models.DateField(blank=True, null=True),
        ),
    ]
