# Generated by Django 4.2.5 on 2023-09-14 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0020_alter_candidate_finished_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='started_job',
            field=models.DateField(blank=True, null=True),
        ),
    ]
